import uuid
from datetime import datetime
from typing import List, Optional
from sqlalchemy import (
    String,
    ForeignKey,
    Boolean,
    Index,
    text,
    func,
    Float,
    DateTime,
    Integer,
    BigInteger,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID, JSONB
from dal.base import Base


class AuthorProfile(Base):
    """
    The Global Identity Node for CoreGraph.
    Consolidates multiple personas (GitHub, NPM, PyPI) into a single analytical entity
    to track high-fidelity social engineering risk across ecosystems.
    """

    __tablename__ = "author_profiles"

    id: Mapped[uuid.UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        doc="Primary 128-bit identifier for the human actor.",
    )

    # PRIVACY-PRESERVING IDENTITY
    email_hash: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        index=True,
        nullable=False,
        doc="SHA-256 hash of the author's primary email address (GDPR compliant linking).",
    )

    display_name: Mapped[Optional[str]] = mapped_column(
        String(255), doc="Publicly visible handle or name."
    )

    github_id: Mapped[Optional[str]] = mapped_column(
        String(128),
        index=True,
        unique=True,
        doc="Canonical GitHub identifier for API-based cross-referencing.",
    )

    # REPUTATION TELEMETRY
    global_reputation_score: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        server_default=text("0.0"),
        doc="Normalized trust score (0.0-100.0) generated by the i9's reputation engine.",
    )

    is_verified_maintainer: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        server_default=text("false"),
        doc="Manual or automated verification status of the identity node.",
    )

    # IDENTITY ALIASES (Multi-Ecosystem Mapping)
    identity_metadata: Mapped[dict] = mapped_column(
        JSONB,
        server_default=text("'{}'"),
        doc="Vault for ecosystem-specific handles, GPG keys, and AI-derived intent analysis.",
    )

    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        doc="Initial temporal marker for the contributor's global footprint.",
    )

    # RELATIONSHIPS
    metrics: Mapped[List["MaintainerMetrics"]] = relationship(
        "MaintainerMetrics", back_populates="author", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("ix_author_metadata_gin", "identity_metadata", postgresql_using="gin"),
        Index("ix_author_reputation", "global_reputation_score"),
    )

    def __repr__(self) -> str:
        return f"<AuthorProfile(id={self.id}, display_name='{self.display_name}', score={self.global_reputation_score})>"


class MaintainerMetrics(Base):
    """
    The Behavioral Telemetry Vault.
    Tracks the activity, velocity, and social engineering risk of an author
    relative to a specific package node in the CoreGraph matrix.
    """

    __tablename__ = "maintainer_metrics"

    id: Mapped[uuid.UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )

    # LINKAGE
    package_id: Mapped[uuid.UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("packages.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
        doc="The target package node being maintained.",
    )

    author_id: Mapped[uuid.UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("author_profiles.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
        doc="The identity node responsible for the code changes.",
    )

    # QUANTITATIVE BEHAVIORAL DATA
    commit_count_90d: Mapped[int] = mapped_column(
        Integer,
        default=0,
        server_default=text("0"),
        doc="Total commit count in a rolling 90-day investigative window.",
    )

    lines_added_90d: Mapped[int] = mapped_column(
        BigInteger,
        default=0,
        server_default=text("0"),
        doc="Cumulative lines of code introduced by the actor.",
    )

    lines_removed_90d: Mapped[int] = mapped_column(
        BigInteger,
        default=0,
        server_default=text("0"),
        doc="Cumulative lines of code removed (detecting massive refactors/pruning).",
    )

    # VELOCITY CALCULUS
    current_velocity: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        server_default=text("0.0"),
        doc="First derivative of activity over time (Work Density scalar).",
    )

    velocity_delta_30d: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        server_default=text("0.0"),
        doc="Volatility detector: identifies sudden spikes suggestive of account subversion.",
    )

    # SOCIAL ENGINEERING RISK MAPPING
    se_risk_score: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        server_default=text("0.0"),
        doc="Quantized threat level (0.0 to 1.0) derived from behavioral patterns.",
    )

    risk_justification: Mapped[Optional[str]] = mapped_column(
        String(1024), doc="Plain-text or AI-derived evidence supporting the current se_risk_score."
    )

    last_active_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        doc="Last recorded activity timestamp on the specific package node.",
    )

    # RELATIONSHIPS
    author: Mapped["AuthorProfile"] = relationship("AuthorProfile", back_populates="metrics")
    package: Mapped["Package"] = relationship("Package", back_populates="maintainer_metrics")

    # CONSTRAINTS & OPTIMIZED LOOKUPS
    __table_args__ = (
        # Uniqueness: One identity node per package behavioral profile.
        Index("uq_author_package_metrics", "author_id", "package_id", unique=True),
        # High-Risk Maintainer Index: Faster audits for critical security vectors.
        Index(
            "ix_high_risk_maintainers",
            "se_risk_score",
            postgresql_where=(text("se_risk_score > 0.7")),
        ),
    )

    def __repr__(self) -> str:
        return f"<MaintainerMetrics(auth_id={self.author_id}, pkg_id={self.package_id}, risk={self.se_risk_score})>"
