"""initial_osint_persistence_vault

Revision ID: aa2b165818d6
Revises:
Create Date: 2026-03-21 22:09:19.658218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa2b165818d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=128), nullable=True),
    sa.Column('global_reputation_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('is_verified_maintainer', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('identity_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_author_metadata_gin', 'author_profiles', ['identity_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_author_profiles_email_hash'), 'author_profiles', ['email_hash'], unique=True)
    op.create_index(op.f('ix_author_profiles_github_id'), 'author_profiles', ['github_id'], unique=True)
    op.create_index('ix_author_reputation', 'author_profiles', ['global_reputation_score'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ecosystem', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_latest', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem', 'name', name='uq_package_ecosystem_name')
    )
    op.create_index('ix_package_name_lower_unique', 'packages', [sa.literal_column('lower(name)'), sa.literal_column('lower(ecosystem)')], unique=True)
    op.create_index('ix_package_name_trgm', 'packages', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=True)
    op.create_table('maintainer_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('commit_count_90d', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lines_added_90d', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('lines_removed_90d', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_velocity', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('velocity_delta_30d', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('se_risk_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('risk_justification', sa.String(length=1024), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_high_risk_maintainers', 'maintainer_metrics', ['se_risk_score'], unique=False, postgresql_where=sa.text('se_risk_score > 0.7'))
    op.create_index(op.f('ix_maintainer_metrics_author_id'), 'maintainer_metrics', ['author_id'], unique=False)
    op.create_index(op.f('ix_maintainer_metrics_package_id'), 'maintainer_metrics', ['package_id'], unique=False)
    op.create_index('uq_author_package_metrics', 'maintainer_metrics', ['author_id', 'package_id'], unique=True)
    op.create_table('package_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=128), nullable=False),
    sa.Column('semver_sort_index', sa.BigInteger(), nullable=True),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['package_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'version_string', name='uq_package_version_string')
    )
    op.create_index('ix_package_version_metadata_gin', 'package_versions', ['metadata_extra'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_package_versions_package_id'), 'package_versions', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_versions_release_date'), 'package_versions', ['release_date'], unique=False)
    op.create_index(op.f('ix_package_versions_semver_sort_index'), 'package_versions', ['semver_sort_index'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=False),
    sa.Column('child_package_id', sa.UUID(), nullable=False),
    sa.Column('specifier', sa.String(length=128), nullable=False),
    sa.Column('is_development', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_optional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['package_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_edges_child_package_id'), 'dependency_edges', ['child_package_id'], unique=False)
    op.create_index(op.f('ix_dependency_edges_parent_version_id'), 'dependency_edges', ['parent_version_id'], unique=False)
    op.create_index('ix_dependency_forward_traversal', 'dependency_edges', ['parent_version_id', 'child_package_id', 'is_development'], unique=False, postgresql_using='btree')
    op.create_index('ix_dependency_reverse_traversal', 'dependency_edges', ['child_package_id', 'parent_version_id', 'is_development'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dependency_reverse_traversal', table_name='dependency_edges', postgresql_using='btree')
    op.drop_index('ix_dependency_forward_traversal', table_name='dependency_edges', postgresql_using='btree')
    op.drop_index(op.f('ix_dependency_edges_parent_version_id'), table_name='dependency_edges')
    op.drop_index(op.f('ix_dependency_edges_child_package_id'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_package_versions_semver_sort_index'), table_name='package_versions')
    op.drop_index(op.f('ix_package_versions_release_date'), table_name='package_versions')
    op.drop_index(op.f('ix_package_versions_package_id'), table_name='package_versions')
    op.drop_index('ix_package_version_metadata_gin', table_name='package_versions', postgresql_using='gin')
    op.drop_table('package_versions')
    op.drop_index('uq_author_package_metrics', table_name='maintainer_metrics')
    op.drop_index(op.f('ix_maintainer_metrics_package_id'), table_name='maintainer_metrics')
    op.drop_index(op.f('ix_maintainer_metrics_author_id'), table_name='maintainer_metrics')
    op.drop_index('ix_high_risk_maintainers', table_name='maintainer_metrics', postgresql_where=sa.text('se_risk_score > 0.7'))
    op.drop_table('maintainer_metrics')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_index('ix_package_name_trgm', table_name='packages', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_package_name_lower_unique', table_name='packages')
    op.drop_table('packages')
    op.drop_index('ix_author_reputation', table_name='author_profiles')
    op.drop_index(op.f('ix_author_profiles_github_id'), table_name='author_profiles')
    op.drop_index(op.f('ix_author_profiles_email_hash'), table_name='author_profiles')
    op.drop_index('ix_author_metadata_gin', table_name='author_profiles', postgresql_using='gin')
    op.drop_table('author_profiles')
    # ### end Alembic commands ###
