import uuid
from datetime import datetime
from typing import Any, Dict

from pydantic import BaseModel, ConfigDict, Field, SecretStr


def _inject_nested_descriptions(schema: Dict[str, Any]) -> None:
    """
    Recursively injects strictly formatted descriptions into the relational
    properties generated by nested Pydantic models.
    """
    if "properties" in schema:
        for prop_name, prop_data in schema["properties"].items():
            if "description" not in prop_data:
                prop_data["description"] = (
                    f"Relational binding mapping the {prop_name} attribute "
                    "within the global topology."
                )

            if "items" in prop_data and isinstance(prop_data["items"], dict):
                _inject_nested_descriptions(prop_data["items"])
            if "allOf" in prop_data or "anyOf" in prop_data:
                for sub in prop_data.get("allOf", []) + prop_data.get("anyOf", []):
                    _inject_nested_descriptions(sub)


class EnhancedBaseModel(BaseModel):
    """
    Strict architectural base model enforcing documentation transparency.
    """

    model_config = ConfigDict(from_attributes=True, json_schema_extra=_inject_nested_descriptions)


class PackageSchema(EnhancedBaseModel):
    id: uuid.UUID = Field(
        ...,
        description=(
            "The 128-bit relational primary key universally identifying the "
            "package within the PostgreSQL vault."
        ),
        examples=["4f1d4b68-6c8f-431e-a4b5-4b0d0c3ebc9c"],
    )
    ecosystem: str = Field(
        ...,
        max_length=50,
        description=(
            "The package registry nomenclature strictly bound to the origin "
            "repository (e.g., NPM, PyPI)."
        ),
        examples=["NPM"],
    )
    name: str = Field(
        ...,
        max_length=200,
        description=(
            "The canonical structural identifier required for acyclic graph " "resolution."
        ),
        examples=["react"],
    )
    latest_version: str | None = Field(
        None,
        description=(
            "The semantic versioning string representing the most recent " "repository commit."
        ),
    )
    created_at: datetime = Field(
        ...,
        description=(
            "The strict chronological timestamp tracking initial ingestion "
            "into the relational cache."
        ),
    )


class DependencyEdgeSchema(EnhancedBaseModel):
    id: uuid.UUID = Field(
        ...,
        description=("The definitive structural edge identifier within the DAG."),
    )
    source_package: PackageSchema = Field(
        ..., description="The downstream parent referencing the dependency."
    )
    target_package: PackageSchema = Field(
        ...,
        description=("The upstream dependency target forming the structural foundation."),
    )
    is_direct: bool = Field(
        ...,
        description=("A boolean flag defining immediate vs transitive dependency risk."),
    )


class IngestRequestSchema(EnhancedBaseModel):
    ecosystem: str = Field(
        ..., max_length=50, description="The targeted package ecosystem repository."
    )
    name: str = Field(
        ...,
        max_length=200,
        description=("The precise canonical name of the dependency target."),
    )


class IngestResponseSchema(EnhancedBaseModel):
    task_id: str = Field(
        ...,
        description=(
            "The UUID tracking the execution context mapped to the 16-worker " "Celery pool."
        ),
    )
    status: str = Field(
        ...,
        description=(
            "The immediate synchronization status of the asynchronous " "ingestion request."
        ),
    )


class AuthSchema(EnhancedBaseModel):
    access_token: SecretStr = Field(
        ..., description="The bearer token managing the session context."
    )
