# scripts/purge_development_artifacts.py

import os
import shutil
import glob
from pathlib import Path

def execution_purge_protocol():
    """
    The Final Janitor of Module 2.
    Ensures that no prototyping artifacts remain in the repository. (Task 027).
    """
    targets = [
        "*.sqlite", "*.sqlite3", "temp.db", # Prototyping DBs
        "**/sql_scratchpad.sql",            # Ad-hoc scripts
        "alembic.ini",                      # OLD ROOT LEVEL
        "alembic/",                         # OLD ROOT LEVEL
        "test_*.bin",                       # Temporary binary dumps
        "**/__pycache__/**",                # Bytecode
        "stress_test_db.py",                # Obsolete prototyping test
        "**/explain_analyze_test.sql"       # Performance ad-hoc results
    ]
    
    # We also check for 'backend/.env' (duplicate of root .env often generated by installers)
    if os.path.exists("backend/.env"):
        targets.append("backend/.env")

    print("[PURGE] Initiating Section 4 Compliance Protocol...")
    
    root_path = Path.cwd()
    
    for pattern in targets:
        files = glob.glob(str(root_path / pattern), recursive=True)
        for f in files:
            p = Path(f)
            # CRITICAL: We skip files inside the 'backend/dal' hardened directory
            # and our specialized migrations/triggers.
            if "backend/dal" in str(p.as_posix()):
                continue 
            
            try:
                if p.is_file():
                    p.unlink()
                    print(f"[CLEANED] Removed file: {p.relative_to(root_path)}")
                elif p.is_dir():
                    shutil.rmtree(p)
                    print(f"[CLEANED] Removed directory: {p.relative_to(root_path)}")
            except Exception as e:
                print(f"[ERROR] Failed to purge {p}: {e}")

    # VERIFY ROOT OBSTRUCTION (SECTION 5)
    # The root must contain only: backend/, docs/, infrastructure/, Makefile, docker-compose.yml, .env, .workspace/
    print("\n[AUDIT] Verifying Root-Level Segregation...")
    permitted = {
        "backend", "docs", "infrastructure", "Makefile", "docker-compose.yml", 
        ".env", ".workspace", "scripts", "venv", ".git", ".github", ".gitignore",
        ".pre-commit-config.yaml", ".flake8", ".dockerignore", ".firebaserc",
        "firebase.json", "alembic.ini", ".githooks", "logs", ".mypy_cache", ".seal-include"
    }
    
    actual = {item.name for item in root_path.iterdir()}
    violations = actual - permitted
    
    if violations:
        print(f"[WARNING] Potential root violations detected: {violations}")
    else:
        print("[SUCCESS] CoreGraph Root is surgically clean.")

if __name__ == "__main__":
    execution_purge_protocol()
