# Redis configuration with ACLs

# Disable unprotected mode
protected-mode yes

# Bind inside container
bind 0.0.0.0

# Disable default user commands
user default off

# Ingestion User: only ingestion/default queues
user ingestion on >ingestpassword123 ~ingestion* ~default* +@all
user analytical on >analyticspassword123 ~analytics* ~graph_state* +@all
user gateway on >gatewaypassword123 ~* +@read
