"""Add topological name normalization and sync uix constraint

Revision ID: d91352b66cdb
Revises: e5e9c92918a5
Create Date: 2026-03-21 14:56:22.210081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d91352b66cdb"
down_revision: Union[str, Sequence[str], None] = "e5e9c92918a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("dependencies_source_package_id_fkey"), "dependencies", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencies_target_package_id_fkey"), "dependencies", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "dependencies",
        "packages",
        ["source_package_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "dependencies",
        "packages",
        ["target_package_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "financial_health",
        "annual_budget_usd",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "financial_health",
        "current_balance_usd",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=2),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("financial_health_package_id_key"), "financial_health", type_="unique")
    op.create_index(
        op.f("ix_financial_health_package_id"),
        "financial_health",
        ["package_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("financial_health_package_id_fkey"), "financial_health", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "financial_health", "packages", ["package_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("maintainer_health_package_id_key"), "maintainer_health", type_="unique"
    )
    op.create_index(
        op.f("ix_maintainer_health_package_id"),
        "maintainer_health",
        ["package_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("maintainer_health_package_id_fkey"),
        "maintainer_health",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "maintainer_health",
        "packages",
        ["package_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("packages", sa.Column("name_normalized", sa.String(), nullable=False))
    op.drop_constraint(op.f("uix_ecosystem_name"), "packages", type_="unique")
    op.create_index(
        op.f("ix_packages_name_normalized"),
        "packages",
        ["name_normalized"],
        unique=False,
    )
    op.create_unique_constraint(
        "uix_ecosystem_name_norm", "packages", ["ecosystem", "name_normalized"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_ecosystem_name_norm", "packages", type_="unique")
    op.drop_index(op.f("ix_packages_name_normalized"), table_name="packages")
    op.create_unique_constraint(
        op.f("uix_ecosystem_name"),
        "packages",
        ["ecosystem", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("packages", "name_normalized")
    op.drop_constraint(None, "maintainer_health", type_="foreignkey")
    op.create_foreign_key(
        op.f("maintainer_health_package_id_fkey"),
        "maintainer_health",
        "packages",
        ["package_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_maintainer_health_package_id"), table_name="maintainer_health")
    op.create_unique_constraint(
        op.f("maintainer_health_package_id_key"),
        "maintainer_health",
        ["package_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "financial_health", type_="foreignkey")
    op.create_foreign_key(
        op.f("financial_health_package_id_fkey"),
        "financial_health",
        "packages",
        ["package_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_financial_health_package_id"), table_name="financial_health")
    op.create_unique_constraint(
        op.f("financial_health_package_id_key"),
        "financial_health",
        ["package_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "financial_health",
        "current_balance_usd",
        existing_type=sa.Numeric(precision=18, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "financial_health",
        "annual_budget_usd",
        existing_type=sa.Numeric(precision=18, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_constraint(None, "dependencies", type_="foreignkey")
    op.drop_constraint(None, "dependencies", type_="foreignkey")
    op.create_foreign_key(
        op.f("dependencies_target_package_id_fkey"),
        "dependencies",
        "packages",
        ["target_package_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("dependencies_source_package_id_fkey"),
        "dependencies",
        "packages",
        ["source_package_id"],
        ["id"],
    )
    # ### end Alembic commands ###
