"""Initial schema

Revision ID: e5e9c92918a5
Revises:
Create Date: 2026-03-21 12:31:10.870744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e5e9c92918a5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ecosystem", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latest_version", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecosystem", "name", name="uix_ecosystem_name"),
    )
    op.create_index(op.f("ix_packages_id"), "packages", ["id"], unique=False)
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_package_id", sa.Uuid(), nullable=False),
        sa.Column("target_package_id", sa.Uuid(), nullable=False),
        sa.Column("version_requirement", sa.String(), nullable=True),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_package_id"],
            ["packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dependencies_source_package_id"),
        "dependencies",
        ["source_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependencies_target_package_id"),
        "dependencies",
        ["target_package_id"],
        unique=False,
    )
    op.create_table(
        "financial_health",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("funding_platform", sa.String(), nullable=True),
        sa.Column("platform_slug", sa.String(), nullable=True),
        sa.Column("annual_budget_usd", sa.Float(), nullable=False),
        sa.Column("current_balance_usd", sa.Float(), nullable=False),
        sa.Column("is_commercially_backed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_id"),
    )
    op.create_table(
        "maintainer_health",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("github_repo_url", sa.String(), nullable=True),
        sa.Column("commit_velocity_30d", sa.Integer(), nullable=False),
        sa.Column("active_maintainers_count", sa.Integer(), nullable=False),
        sa.Column("last_commit_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("open_issues_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maintainer_health")
    op.drop_table("financial_health")
    op.drop_index(op.f("ix_dependencies_target_package_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_source_package_id"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_packages_id"), table_name="packages")
    op.drop_table("packages")
    # ### end Alembic commands ###
